UrBoyBae/ngaoskuy-media

app/Http/Controllers/User/DashboardController.php
app/Http/Controllers/User/QuestionController.php
app/Http/Controllers/User/VideoListController.php
app/Http/Controllers/User/VideoPlayerController.php

Ganti nama title dan penambahan pemanggilan database pada semua index di role user

arya, bugfixes/UserController-MinorFix

---

app/Http/Controllers/Member/ChatController.php
app/Http/Controllers/Member/KitabController.php
app/Http/Controllers/Member/QuestionController.php
app/Http/Controllers/Member/VideoListController.php
app/Http/Controllers/Member/VideoPlayerController.php

arya, bugfixes/MemberController

---

resources/js/app.js
resources/views/components/templates/splash-screen.blade.php

Penyesuaian pada semua button yang ada di splash screen agar ketika diklik itu meng-direct ke halaman login dan ke dashboard dengan role user

ali, features/update-button-on-splash-screen

---

app/Http/Controllers/Admin/DashboardController.php
app/Http/Controllers/Member/ChatController.php

Minor Bug Fixes
- Admin/DashboardController
- Member/ChatController

arya, bugfixes/AdminController-and-ChatController@Member

---

resources/js/app.js
resources/views/components/organisme/navbar.blade.php
resources/views/components/templates/dashboard.blade.php
resources/views/layouts/index.blade.php
routes/web.php

Merubah sidebar dan navbar menjadi seperti difigma, dan menambahkan form pada button logout

ali, features/update-sidebar-and-navbar

---

resources/views/components/organisme/navbar.blade.php

kevin, features/create-logout-function

---

app/Http/Controllers/Admin/EpisodeController.php
composer.lock

- API Hit for Episode Created
- GuzzleHTTP added for API hitting

arya, feature/AdminControllerJudul

---

app/Http/Controllers/RegistrasionController.php
database/migrations/2023_12_26_133445_create_detail_users_table.php
database/seeders/DatabaseSeeder.php
resources/views/regis.blade.php
routes/web.php

kevin, features/create-registrasion

---

app/Http/Controllers/Ustadz/ArticleController.php
app/Http/Controllers/Ustadz/DashboardController.php
app/Http/Controllers/Ustadz/PertanyaanController.php
app/Http/Controllers/Ustadz/VideoController.php

pembuatan controller di role ustadz dengan controller
- Dashboard
- Artikel
- Pertanyaan
- Video

arya, feature/UstadzController

---

app/Http/Controllers/AuthController.php
app/Http/Controllers/Member/DashboardController.php
app/Http/Controllers/Member/QuestionController.php
app/Models/Question.php
database/migrations/2023_12_26_133907_create_questions_table.php
routes/web.php

- Pengelompokkan Middleware di Route
- Percobaan Penambahan pertanyaan pada role Member

arya, bugfix/MemberQuestionTesting

---

app/Http/Controllers/AuthController.php
app/Http/Controllers/Member/DashboardController.php
app/Http/Middleware/RoleMiddleware.php
resources/views/components/organisme/navbar.blade.php
routes/web.php

Error handling ketika user tidak ditemukan

kevin, login-invalid-user-handle

---

app/Http/Controllers/Member/DashboardController.php
app/Models/Bab.php
app/Models/Episode.php
app/Models/Judul.php
app/Models/Kitab.php
app/Models/SubBab.php
routes/web.php

Fetching data from kitab database error, fixed

arya, bugfix/MemberDashboardController

---

resources/views/components/templates/about-us.blade.php

makasih arya, kata pasha
Pembuatan hidden, nonhidden di about us

arya, bugfix/AboutUsKepunyaanPasha

---

app/Http/Controllers/Admin/DashboardController.php
app/Http/Controllers/AuthController.php
app/Http/Controllers/Member/DashboardController.php
app/Http/Controllers/User/DashboardController.php
app/Http/Controllers/Ustadz/DashboardController.php
database/seeders/ArticleSeeder.php
database/seeders/DatabaseSeeder.php
database/seeders/QuestionSeeder.php
resources/views/admin/dashboard.blade.php
resources/views/components/organisme/navbar.blade.php
resources/views/member/dashboard.blade.php
resources/views/user/dashboard.blade.php
resources/views/ustadz/dashboard.blade.php
routes/web.php

arya, bugfix/LoginDummyViewsPerRole

---

app/Http/Controllers/Admin/ArticleController.php
app/Http/Controllers/Admin/BabController.php
app/Http/Controllers/Admin/EpisodeController.php
app/Http/Controllers/Admin/SubBabController.php
app/Http/Controllers/Member/ArticleController.php
app/Http/Controllers/Member/ChatController.php
app/Http/Controllers/Member/QuestionController.php
app/Http/Controllers/Member/VideoListController.php
app/Http/Controllers/User/ArticleController.php
app/Http/Controllers/User/QuestionController.php
app/Http/Controllers/User/VideoListController.php
app/Http/Controllers/Ustadz/ArticleController.php
app/Http/Controllers/Ustadz/PertanyaanController.php
app/Http/Controllers/Ustadz/VideoController.php

$kitab = Kitab::with(['bab', 'subbab', 'judul', 'episode'])->get(); -> $kitab = Kitab::with(['bab'])->get();

arya, bugfix/KitabFixedFethcing

---

app/Http/Controllers/User/QuestionController.php
resources/views/user/question.blade.php

fixed question controller to returning view

arya, bugfix/QuestionController

---

app/Http/Controllers/User/ArticleController.php
app/Http/Controllers/User/DashboardController.php
app/Http/Controllers/User/QuestionController.php
app/Http/Controllers/User/VideoListController.php

return view added on every controller on user role

arya, bugfix/UserController

---

app/View/Components/Molekuls/ArticleCard.php
app/View/Components/Molekuls/QuestionCard.php
app/View/Components/Organisme/ArticleSlider.php
app/View/Components/Organisme/QuestionSlider.php
resources/css/app.css
resources/js/app.js
resources/views/components/molekuls/article-card.blade.php
resources/views/components/molekuls/question-card.blade.php
resources/views/components/organisme/article-slider.blade.php
resources/views/components/organisme/episode-slider.blade.php
resources/views/components/organisme/question-slider.blade.php
resources/views/components/templates/dashboard.blade.php
resources/views/layouts/index.blade.php

Membuat Halaman Dashboard untuk role user

ali, features/create-user-home-page

---

resources/views/components/templates/user/video/index.blade.php

ali, features/create-index-video-page

---

app/Http/Controllers/AboutUsController.php
routes/web.php

membuat controller untuk halaman about us

kevin, features/create-about-us-controller

---

app/Http/Controllers/PhotoGalleryController.php
routes/web.php

Membuat controller untuk halaman galeri photo

kevin, features/create-photo-galleries-controllers

---

app/Http/Controllers/RegistrasionController.php
app/View/Components/Molekuls/QuestionCard.php
resources/views/components/molekuls/question-card.blade.php
resources/views/components/organisme/footer.blade.php
resources/views/components/templates/user/dashboard/index.blade.php
resources/views/components/templates/user/question/index.blade.php
resources/views/layouts/index.blade.php

Membuat Halaman index question untuk role user

ali, features/features/create-index-question-page

---

app/Http/Controllers/AuthController.php
app/Http/Middleware/RoleMiddleware.php
routes/web.php

memperbaiki bug pada saat login berhasil ke halaman dashboard masing-masing role

kevin, bugfix/login-dashboard-redirect

---

app/Http/Controllers/Admin/DashboardController.php
app/Http/Controllers/AuthController.php
app/Http/Controllers/Member/DashboardController.php
app/Http/Controllers/Ustadz/DashboardController.php
app/Http/Middleware/RedirectIfAuthenticated.php
app/Providers/RouteServiceProvider.php
resources/views/components/templates/admin/dashboard/index.blade.php
routes/web.php

memperbaiki redirect dashboard masing-masing role dan merapihkan file route

kevin, bugfix origin bugfix/home-page-role

---

resources/views/components/templates/user/article/index.blade.php

Membuat halaman index artikel untuk role user

ali, features/create-index-article-page

---

resources/css/app.css
resources/js/app.js
resources/views/authentication/registrasi.blade.php
resources/views/components/organisme/footer.blade.php

meng-update komponen footer dan meng-update button register serta email

aca, features/update-footer-component

---

resources/views/components/templates/user/question/show.blade.php

ali, features/creates-show-question-page

---

app/Http/Controllers/User/ArticleController.php
app/Http/Controllers/User/QuestionController.php
app/Models/Question.php
app/Models/User.php
database/seeders/ArticleSeeder.php
resources/js/app.js
resources/views/components/organisme/episode-slider.blade.php
resources/views/components/templates/user/article/index.blade.php
resources/views/components/templates/user/question/index.blade.php

selain question dan article, 
Slider episode pada slider juga udah jadi dinamis sesuai sama episode

arya, bugfix/Question-Article-Controller

---

resources/views/components/templates/user/article/show.blade.php

aca, features/create-show-article-page

---

app/Http/Controllers/User/QuestionController.php
app/Models/Chat.php
app/Models/ChatDetail.php
database/seeders/ChatDetailSeeder.php
database/seeders/ChatSeeder.php
database/seeders/DatabaseSeeder.php
resources/views/components/templates/user/question/show.blade.php

- Question Controller Bug Fixed
- Chat Detail Seeder
- Chat Seeder 
- Question Seeder Minor Fix
- show.blade.php udah dinamis

arya, bugfix/Chat-User-BugFixed

---

app/Http/Controllers/User/ArticleController.php
database/seeders/ArticleSeeder.php
resources/views/components/templates/user/article/index.blade.php
resources/views/components/templates/user/article/show.blade.php

- Article Controller
- Article Seeder
- Article View Index
- Article View Show

arya, bugfix/Article-Core

---

app/Http/Controllers/Member/QuestionController.php
resources/views/components/templates/member/dashboard/index.blade.php
resources/views/components/templates/user/dashboard/index.blade.php

membuat halaman dashboard untuk member

aca, features/create-index-dashboard-member-page

---

app/Http/Controllers/User/VideoListController.php
resources/views/components/templates/user/video/show.blade.php

Membuat halaman show video page

ali, features/create-show-video-page

---

resources/css/app.css
resources/views/components/organisme/footer.blade.php
resources/views/components/organisme/navbar.blade.php

penyesuaian ukuran navbar dan sidebar pada reso andro dan laptop, karena kondisi saat ini ukuran nya terlalu kecil.

ajizah, features/update-sidebar-and-navbar-2

---

app/Http/Controllers/User/VideoListController.php
resources/views/components/templates/user/video/show.blade.php
routes/web.php

- VideolistController dari user
- Tambahan Route display untuk video list
- video sudah dinamis

arya, bugfix/Video-Show-User

---

app/Http/Controllers/Member/QuestionController.php

return view('components.templates.member.question.create')

arya, feature/question-controller-update

---

app/Http/Controllers/AboutUsController.php
app/Http/Controllers/Admin/DashboardController.php
app/Http/Controllers/Member/DashboardController.php
app/Http/Controllers/User/DashboardController.php
app/Http/Controllers/Ustadz/DashboardController.php
resources/views/components/templates/member/dashboard/index.blade.php
routes/web.php

Memperbaiki bug saat menekan judul aplikasi yang mengarahkan user ke dashboard masing-masing

kevin, bugfix/ngaos-kuy-redirect

---

resources/js/app.js
resources/views/components/organisme/navbar.blade.php
resources/views/components/templates/member/dashboard/index.blade.php

ali, features/create-modal-setting-profile

---

app/Http/Controllers/User/ArticleController.php
app/Http/Controllers/User/QuestionController.php
app/Http/Controllers/User/VideoListController.php
app/Http/Controllers/Ustadz/DashboardController.php
resources/views/components/templates/user/article/index.blade.php
resources/views/components/templates/user/question/index.blade.php
resources/views/components/templates/user/video/index.blade.php
tailwind.config.js

Membuat pagination pada halaman pertanyaan dan artikel

kevin, features/pagination

---

resources/views/components/templates/member/question/create.blade.php
routes/web.php

membuat halaman tambah pertanyaan pada role member.

ajizah, features/create-add-question-page

---

app/Http/Controllers/Member/DashboardController.php
app/Http/Controllers/Member/QuestionController.php
resources/views/components/templates/member/dashboard/index.blade.php
resources/views/components/templates/member/question/create.blade.php
resources/views/components/templates/member/question/show.blade.php

minus penambahan view episode, karena belum dari fe nya

arya, feature/add-question-member

---

resources/views/components/templates/member/question/show.blade.php

Penyesuaian pada input pertanyaan, detail pertanyaan, dan penambahan video terkait di halaman status pertanyaan.

ali, features/update-status-question-page

---

app/Http/Controllers/Member/ChatController.php
app/Http/Controllers/Member/QuestionController.php
resources/views/components/templates/member/question/show.blade.php
routes/web.php

fitur pada show member question untuk menambahkan episode yang berelasi

arya, feature/update-question-show-member

---

app/Http/Controllers/Member/QuestionController.php
resources/views/components/templates/member/question/show.blade.php

bugfix on show question member

arya, bugfix/update-question-show-member

---

resources/css/app.css
resources/views/components/organisme/footer.blade.php

mengupdate tampilan footer menjadi lebih rapih

aca, features/update-footer-all-page

---

database/seeders/EpisodeSeeder.php
resources/views/components/molekuls/video-display.blade.php
resources/views/components/templates/member/question/show.blade.php

1. Penyesuaian pada video terkait pada halaman status pertanyaan. untuk kondisi saat ini belum dirubah menjadi component, karena itu tolong disesuaikan menjadi component. untuk file component nya mengggunakan video-display sama seperti yang ada dihalaman video show.
2. Penyesuian pada component video-display agar width nya menggunakan props yang dikirim. karena saat ini kondisi nya masih hardcode, tolong rubah menjadi dinamis.

ajizah, features/update-video-terkait

---

resources/views/components/templates/member/chat/index.blade.php

Penyesuaian pada tampilan dari form chat di halaman chat index role member. karena untuk saat ini belum sesuai seperti yang ada difigma.

ajizah, features/update-chat-form

---

app/View/Components/Atoms/TabButton.php
resources/js/app.js
resources/views/components/atoms/tab-button.blade.php
resources/views/components/templates/about-us.blade.php

memindahkan javascript dan penyesuaian button 'ngaoskuy' dan 'eunola' menjadi component

aca,features/update-about-us-page

---

resources/js/app.js
resources/views/authentication/registrasi.blade.php

menambahkan input dengan id dan name nya itu nama, dan menyesuaikan juga validasi javascript nya

aca, features/create-name-input-on-register

---

app/Http/Controllers/Member/VideoListController.php
app/Http/Controllers/Ustadz/ArticleController.php
app/Http/Controllers/Ustadz/PertanyaanController.php
resources/views/components/templates/member/chat/index.blade.php
resources/views/components/templates/ustadz/dashboard/index.blade.php
routes/web.php

membuat halaman dashboard dengan role ustadz.

ajizah, features/create-dashboard-role-ustadz

---

app/Http/Controllers/Ustadz/ArticleController.php
resources/views/components/templates/ustadz/article/index.blade.php

membuat halaman article dengan role ustadz.

ajizah, features/create-article-index-role-ustadz

---

app/Http/Controllers/Ustadz/ArticleController.php
resources/views/components/templates/ustadz/article/show.blade.php

membuat halaman show article dengan role ustadz.

ajizah, features/create-article-show-role-ustadz

---

app/Http/Controllers/DownloadController.php
composer.json
composer.lock
resources/views/components/templates/member/video/show.blade.php
routes/web.php

Membuat fitur untuk mendownload video dan juga audio dari channel youtube Ngaos Kuy

kevin, features/video-audio-youtube-downloader

---

app/Http/Controllers/Ustadz/VideoController.php
resources/views/components/templates/ustadz/video/index.blade.php

membuat halaman video index dengan role ustadz

aca, features/create-video-index-role-ustadz

---

app/Http/Controllers/Ustadz/VideoController.php
resources/views/components/templates/ustadz/video/show.blade.php

membuat halaman video show dengan role ustadz tapi ada error

aca, features/create-video-show-role-ustadz

---

app/Http/Controllers/Ustadz/ArticleController.php
resources/views/components/templates/member/question/create.blade.php
resources/views/components/templates/ustadz/article/create.blade.php
resources/views/components/templates/ustadz/article/edit.blade.php
resources/views/components/templates/ustadz/article/index.blade.php

membuat halaman tambah dan edit article dengan role ustad.

ajizah, features/create-article-crud-role-ustadz

---

app/Http/Controllers/Member/ChatController.php
app/Http/Controllers/Ustadz/QuestionController.php
routes/web.php

membuat fitur tanya jawab (chat) untuk role ustadz

kevin, features/create-chat-ustadz

---

resources/views/components/templates/member/question/create.blade.php
resources/views/components/templates/ustadz/article/create.blade.php
resources/views/components/templates/ustadz/article/edit.blade.php

Penyesuaian pada button back dan save karena kondisi saat ini ketika diklik button nya membesar.

ajizah, features/update-button-back-save

---

resources/views/components/templates/member/question/create.blade.php
resources/views/components/templates/ustadz/article/create.blade.php
resources/views/components/templates/ustadz/article/edit.blade.php

Penyesuaian pada input isi artikel, karena kondisi sekarang input nya masih belum rapih.

ajizah, features/update-input-isi-artikel

---

app/Http/Controllers/Member/DashboardController.php
app/Http/Controllers/Member/QuestionController.php

Memperbaiki bug dimana pertanyaan untuk role member tidak bisa ditambah dan memperbaiki urutan dari pertanyaan yang tampil

kevin, bugfix/member-question-create

---

resources/views/components/templates/member/video/index.blade.php
resources/views/components/templates/user/video/index.blade.php
resources/views/components/templates/ustadz/video/index.blade.php

mengupdate judul pada halaman video pada tampilan mobile.

ajizah, features/update-judul-halaman-video-mobile

---

resources/js/app.js
resources/views/components/organisme/navbar.blade.php

penyesuaian pada modal delete article dan sidebar ketika diklik diluar modal akan close

ali, features/close-component-on-click-outside

---

app/Http/Controllers/DownloadController.php
app/Http/Controllers/Member/VideoListController.php
composer.json
composer.lock
package-lock.json
package.json
resources/views/components/templates/download/pdf/index.blade.php

BISA JUGA JIROKAWOAWOKA
browsershot

arya, feature/pdf-download-spatie

---

resources/views/components/atoms/notification-live.blade.php
resources/views/components/templates/about-us.blade.php
resources/views/components/templates/member/article/index.blade.php
resources/views/components/templates/member/article/show.blade.php
resources/views/components/templates/member/chat/index.blade.php
resources/views/components/templates/member/dashboard/index.blade.php
resources/views/components/templates/member/question/create.blade.php
resources/views/components/templates/member/question/index.blade.php
resources/views/components/templates/member/question/show.blade.php
resources/views/components/templates/member/video/index.blade.php
resources/views/components/templates/member/video/show.blade.php
resources/views/components/templates/photo-gallery.blade.php
resources/views/components/templates/user/article/index.blade.php
resources/views/components/templates/user/article/show.blade.php
resources/views/components/templates/user/dashboard/index.blade.php
resources/views/components/templates/user/question/index.blade.php
resources/views/components/templates/user/question/show.blade.php
resources/views/components/templates/user/video/index.blade.php
resources/views/components/templates/user/video/show.blade.php
resources/views/components/templates/ustadz/article/create.blade.php
resources/views/components/templates/ustadz/article/edit.blade.php
resources/views/components/templates/ustadz/article/index.blade.php
resources/views/components/templates/ustadz/article/show.blade.php
resources/views/components/templates/ustadz/dashboard/index.blade.php
resources/views/components/templates/ustadz/questions/index.blade.php
resources/views/components/templates/ustadz/questions/show.blade.php
resources/views/components/templates/ustadz/video/index.blade.php
resources/views/components/templates/ustadz/video/show.blade.php

membuat notifikasi live pada seluruh role

aca, features/create-notification-live

---

app/Http/Controllers/Member/VideoListController.php
app/Http/Controllers/User/VideoListController.php
app/Http/Controllers/Ustadz/VideoController.php
resources/views/components/templates/member/video/show.blade.php
resources/views/components/templates/user/video/show.blade.php
resources/views/components/templates/ustadz/video/show.blade.php

mengganti **$episode->judul->id_subbab** pada show menjadi **$bab->id**

arya, bugfix/breadcrumbs-fixed

---

app/Http/Controllers/Admin/DashboardController.php
app/Http/Controllers/Member/DashboardController.php
app/Http/Controllers/SettingController.php
app/Http/Controllers/User/DashboardController.php
app/Http/Controllers/Ustadz/DashboardController.php
resources/views/components/organisme/navbar.blade.php
resources/views/components/templates/settings.blade.php
routes/web.php

Membuat fitur setting profile berupa edit nama, username, dan password.

kevin, features/create-setting-profile

---

resources/views/components/templates/ustadz/article/create.blade.php
resources/views/components/templates/ustadz/article/edit.blade.php

Penyesuaian pada button back pada halaman create dan edit artikel dengan role ustadz, untuk saat ini href nya menggunakan url()->previous() tolong diubah menggunakan href yang seperti biasanya. karena terdapat case saat mengakses halaman yang mempunyai href url()->previous() akan terjadi looping

aca, bugfix/update-back-buton

---

app/View/Components/Atoms/BreadcrumbThreeIndex.php
app/View/Components/Atoms/BreadcrumbTwoIndex.php
resources/views/components/atoms/breadcrumb-three-index.blade.php
resources/views/components/atoms/breadcrumb-two-index.blade.php
resources/views/components/templates/about-us.blade.php
resources/views/components/templates/member/article/index.blade.php
resources/views/components/templates/member/article/show.blade.php
resources/views/components/templates/member/chat/index.blade.php
resources/views/components/templates/member/question/index.blade.php
resources/views/components/templates/member/video/index.blade.php
resources/views/components/templates/member/video/show.blade.php
resources/views/components/templates/photo-gallery.blade.php
resources/views/components/templates/user/article/index.blade.php
resources/views/components/templates/user/article/show.blade.php
resources/views/components/templates/user/question/index.blade.php
resources/views/components/templates/user/question/show.blade.php
resources/views/components/templates/user/video/index.blade.php
resources/views/components/templates/user/video/show.blade.php
resources/views/components/templates/ustadz/article/index.blade.php
resources/views/components/templates/ustadz/article/show.blade.php
resources/views/components/templates/ustadz/questions/index.blade.php
resources/views/components/templates/ustadz/questions/show.blade.php
resources/views/components/templates/ustadz/video/index.blade.php
resources/views/components/templates/ustadz/video/show.blade.php

merubah breadcrump menjadi component, kondisi saat ini belum menjadi component. terdapat breadcrump dengan level 2 dan 3

ali, features/update-breadcrump-tocomponent
